export const THEMES = {
  default: {
    name: "Default Purple",
    sidebar: "#0f0e1a",
    sidebarText: "#a78bfa",
    primary: "#6d28d9",
    background: "#f4f5fb",
    pattern: "#c4b5fd33",
    cardBg: "#fff",
  },
  finance: {
    name: "Finance Dark",
    sidebar: "#0a1628",
    sidebarText: "#60a5fa",
    primary: "#1d4ed8",
    background: "#0f172a",
    pattern: "#1e3a5f33",
    cardBg: "#1e293b",
  },
  healthcare: {
    name: "Healthcare",
    sidebar: "#064e3b",
    sidebarText: "#6ee7b7",
    primary: "#059669",
    background: "#f0fdf4",
    pattern: "#bbf7d033",
    cardBg: "#fff",
  },
  retail: {
    name: "Retail Orange",
    sidebar: "#431407",
    sidebarText: "#fdba74",
    primary: "#ea580c",
    background: "#fff7ed",
    pattern: "#fed7aa33",
    cardBg: "#fff",
  },
  tech: {
    name: "Tech Cyan",
    sidebar: "#0c1a2e",
    sidebarText: "#67e8f9",
    primary: "#0891b2",
    background: "#f0f9ff",
    pattern: "#bae6fd33",
    cardBg: "#fff",
  },
};